# Profile Configuration
spring.profiles.active=dev

# PostgreSQL Configuration (for production)
# spring.datasource.url=jdbc:postgresql://localhost:5433/Logistics
# spring.datasource.username=postgres
# spring.datasource.password=1234
# spring.jpa.hibernate.ddl-auto=none
# spring.jpa.properties.hibernate.default_schema=public

# General JPA/Hibernate Configuration
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Disable open-in-view to prevent lazy loading issues
spring.jpa.open-in-view=false

server.port=8080

# File Upload
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
